name: Fullstack builds and tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-backend:
    name: Build go backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.24.4'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -o ./bin/server ./cmd/server/main.go

  test-backend:
    name: Tests on go backend
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
              go-version: '1.24.4'

        - name: Get dependencies
          run: go mod download

        - name: Run tests
          run: go test ./...

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    env:
      PUBLIC_API_ENDPOINT: '/api'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      - name: Install dependencies
        working-directory: ./web
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: ./web
        run: bun run build
